### PR TITLE
Add server

### PR DESCRIPTION
**Pull request by WGzeyu**

### CODE REVIEW

**Comment by WGzeyu** [comment]
I just found out that he already exists in OriginalDefaultServers.json
However, after I tried to clear the configuration file, bs-zhm.tk was not found in the new configuration file created by the plugin.

**Comment by WGzeyu** [comment]
I tested it again and still couldn't find bs-zhm.tk, so I will reopen it.
`    "_serverHubIPs": [
        "127.0.0.1",
        "bs.tigersserver.xyz",
        "treasurehunters.nz",
        "www.questboard.xyz",
        "bbbear-wgzeyu.gtxcn.com",
        "pantie.xicp.net"
    ]`

**Comment by Zingabopp** [comment]
I added OriginalDefaultServers.json because I removed the ones that weren't active (at the time I looked) or were running an old version of ServerHub and this would give a way for people to keep monitoring those servers. Thanks for the PR.

**Comment by Zingabopp** [comment]
New mod version requires a ServerHub update https://github.com/Zingabopp/BeatSaberMultiplayer/releases/tag/7.1.0-L

**Pull request merged**
